# Use the stable version of NGINX on Alpine 3.20
FROM nginx:stable-alpine3.20

# Copy your HTML and logo files into the NGINX content directory
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./logo.png /usr/share/nginx/html/logo.png
