apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::248189920276:role/EKSNodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::248189920276:role/ofir
      username: ofir
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::248189920276:user/ofir
      username: ofir
      groups:
        - system:masters
