pipeline {
    agent any  
    environment {
        DOCKER_IMAGE = "ofir2608/nginx_logo"  
        EKS_CLUSTER = "commit-ofir-eks"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/ofirtasa/aws_project.git' 
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Use Jenkins credentials to login to Docker Hub
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                        docker build -t $DOCKER_IMAGE:latest ./logo_app
                        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD  
                        docker push $DOCKER_IMAGE:latest  
                        '''
                    }
                }
            }
        }
        stage('Deploy to EKS') {
            steps {
                sh '''
                aws eks update-kubeconfig --region us-east-1 --name $EKS_CLUSTER  
                kubectl set image deployment/nginx-deployment nginx=$DOCKER_IMAGE:latest  
                '''
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully! The Docker image was built and deployed to EKS.'
        }
        failure {
            echo 'Pipeline failed. Please check the logs to troubleshoot the issue.'
        }
    }
}
